const validator = require('validator');
const dns = require('dns').promises;

// Common disposable email domains
const DISPOSABLE_DOMAINS = new Set([
  '10minutemail.com',
  'tempmail.org',
  'guerrillamail.com',
  'mailinator.com',
  'maildrop.cc',
  'temp-mail.org',
  'throwaway.email',
  'getnada.com',
  'sharklasers.com',
  'guerrillamail.de',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'pokemail.net',
  'spam4.me',
  'bccto.me',
  'chacuo.net',
  'dispostable.com',
  'mailnesia.com',
  'mailcatch.com',
  'inboxalias.com',
  'mailmetrash.com',
  'trashmail.net',
  'trashmailer.com',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spamex.com',
  'spamhole.com',
  'spam.la',
  'binkmail.com',
  'bobmail.info',
  'chammy.info',
  'devnullmail.com',
  'letthemeatspam.com',
  'mailin8r.com',
  'mailinator.com',
  'mailinator2.com',
  'mailinator.net',
  'notmailinator.com',
  'reallymymail.com',
  'reconmail.com',
  'safetymail.info',
  'sogetthis.com',
  'spamhereplease.com',
  'superrito.com',
  'thisisnotmyrealemail.com',
  'tradermail.info',
  'veryrealemail.com',
  'wegwerfadresse.de',
  'wegwerfemail.de',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wegwerpmailadres.nl',
  'wetrainbayarea.com',
  'wetrainbayarea.org',
  'wh4f.org',
  'whyspam.me',
  'wilemail.com',
  'willselfdestruct.com',
  'wuzup.net',
  'wuzupmail.net',
  'yeah.net',
  'yopmail.com',
  'yopmail.net',
  'yopmail.org',
  'ypmail.webarnak.fr.eu.org',
  'cool.fr.nf',
  'jetable.fr.nf',
  'nospam.ze.tc',
  'nomail.xl.cx',
  'mega.zik.dj',
  'speed.1s.fr',
  'courriel.fr.nf',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'hootmail.com', // Common typo for hotmail
  'hootmial.com', // Common typo
  'gmaill.com', // Common typo for gmail
  'gmial.com', // Common typo
  'yahooo.com', // Common typo for yahoo
  'outlok.com', // Common typo for outlook
  // Additional popular disposable domains
  '0-mail.com',
  '0clickemail.com',
  '0wnd.net',
  '0wnd.org',
  '1secmail.com',
  '1secmail.org',
  '1secmail.net',
  '20minutemail.com',
  '20minutemail.it',
  '2prong.com',
  '30minutemail.com',
  '3d-painting.com',
  '4warding.com',
  '4warding.net',
  '4warding.org',
  '60minutemail.com',
  '675hosting.com',
  '675hosting.net',
  '675hosting.org',
  '6ip.us',
  '6paq.com',
  '6url.com',
  '75hosting.com',
  '75hosting.net',
  '75hosting.org',
  '7tags.com',
  '9ox.net',
  'a-bc.net',
  'agedmail.com',
  'amilegit.com',
  'amiri.net',
  'amiriindustries.com',
  'anonmails.de',
  'anonymbox.com',
  'antichef.com',
  'antichef.net',
  'antireg.ru',
  'antispam.de',
  'baxomale.ht.cx',
  'beefmilk.com',
  'binkmail.com',
  'bio-muesli.net',
  'bobmail.info',
  'bodhi.lawlita.com',
  'bofthew.com',
  'brefmail.com',
  'bsnow.net',
  'bspamfree.org',
  'bugmenot.com',
  'bumpymail.com',
  'casualdx.com',
  'centermail.com',
  'centermail.net',
  'chacuo.net',
  'chammy.info',
  'childsavetrust.org',
  'chogmail.com',
  'choicemail1.com',
  'cool.fr.nf',
  'correo.blogos.net',
  'cosmorph.com',
  'courriel.fr.nf',
  'courrieltemporaire.com',
  'cubiclink.com',
  'curryworld.de',
  'cust.in',
  'dacoolest.com',
  'dandikmail.com',
  'dayrep.com',
  'dcemail.com',
  'deadaddress.com',
  'deadspam.com',
  'despam.it',
  'despammed.com',
  'devnullmail.com',
  'dfgh.net',
  'digitalsanctuary.com',
  'discardmail.com',
  'discardmail.de',
  'disposableaddress.com',
  'disposableemailaddresses.com',
  'disposableinbox.com',
  'dispose.it',
  'dispostable.com',
  'dodgeit.com',
  'dodgit.com',
  'dodgit.org',
  'donemail.ru',
  'dontreg.com',
  'dontsendmespam.de',
  'dump-email.info',
  'dumpandjunk.com',
  'dumpmail.de',
  'dumpyemail.com',
  'e-mail.com',
  'e-mail.org',
  'e4ward.com',
  'easytrashmail.com',
  'einrot.com',
  'email60.com',
  'emailias.com',
  'emailinfive.com',
  'emailmiser.com',
  'emailsensei.com',
  'emailtemporario.com.br',
  'emailto.de',
  'emailwarden.com',
  'emailx.at.hm',
  'emailxfer.com',
  'emz.net',
  'enterto.com',
  'ephemail.net',
  'etranquil.com',
  'etranquil.net',
  'etranquil.org',
  'evopo.com',
  'explodemail.com',
  'fakeinformation.com',
  'fantasymail.de',
  'filzmail.com',
  'fizmail.com',
  'fleckens.hu',
  'fr33mail.info',
  'frapmail.com',
  'front14.org',
  'fux0ringduh.com',
  'garliclife.com',
  'get1mail.com',
  'get2mail.fr',
  'getonemail.com',
  'getonemail.net',
  'ghosttexter.de',
  'girlsundertheinfluence.com',
  'gishpuppy.com',
  'gmial.com',
  'goemailgo.com',
  'gotmail.com',
  'gotmail.net',
  'gotmail.org',
  'great-host.in',
  'greensloth.com',
  'gsrv.co.uk',
  'guerillamail.biz',
  'guerillamail.com',
  'guerillamail.de',
  'guerillamail.info',
  'guerillamail.net',
  'guerillamail.org',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'haltospam.com',
  'hatespam.org',
  'hidemail.de',
  'hidzz.com',
  'hmamail.com',
  'hopemail.biz',
  'hotpop.com',
  'hulapla.de',
  'ieatspam.eu',
  'ieatspam.info',
  'ihateyoualot.info',
  'imails.info',
  'inboxalias.com',
  'inboxclean.com',
  'inboxclean.org',
  'incognitomail.com',
  'incognitomail.net',
  'incognitomail.org',
  'insorg-mail.info',
  'instant-mail.de',
  'ip6.li',
  'irish2me.com',
  'iwi.net',
  'jetable.com',
  'jetable.fr.nf',
  'jetable.net',
  'jetable.org',
  'jnxjn.com',
  'jourrapide.com',
  'jsrsolutions.com',
  'kasmail.com',
  'kaspop.com',
  'keepmymail.com',
  'killmail.com',
  'killmail.net',
  'kir.ch.tc',
  'klassmaster.com',
  'klassmaster.net',
  'klzlk.com',
  'koszmail.pl',
  'kurzepost.de',
  'lawlita.com',
  'letthemeatspam.com',
  'lhsdv.com',
  'lifebyfood.com',
  'link2mail.net',
  'litedrop.com',
  'lol.ovpn.to',
  'lookugly.com',
  'lopl.co.cc',
  'loveable.de',
  'lr78.com',
  'm4ilweb.info',
  'maboard.com',
  'mail-temporaire.fr',
  'mail.by',
  'mail.mezimages.net',
  'mail2rss.org',
  'mail333.com',
  'mail4trash.com',
  'mailbidon.com',
  'mailbiz.biz',
  'mailblocks.com',
  'mailcatch.com',
  'maildrop.cc',
  'maileater.com',
  'mailexpire.com',
  'mailfa.tk',
  'mailforspam.com',
  'mailfreeonline.com',
  'mailguard.me',
  'mailin8r.com',
  'mailinater.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator2.com',
  'mailincubator.com',
  'mailme.lv',
  'mailmetrash.com',
  'mailmoat.com',
  'mailnesia.com',
  'mailnull.com',
  'mailorg.org',
  'mailpick.biz',
  'mailrock.biz',
  'mailscrap.com',
  'mailshell.com',
  'mailsiphon.com',
  'mailtemp.info',
  'mailtome.de',
  'mailtothis.com',
  'mailtrash.net',
  'mailtv.net',
  'mailtv.tv',
  'mailzilla.com',
  'mailzilla.org',
  'makemetheking.com',
  'manybrain.com',
  'mbx.cc',
  'mciek.com',
  'mega.zik.dj',
  'meltmail.com',
  'messagebeamer.de',
  'mierdamail.com',
  'mintemail.com',
  'mjukglass.nu',
  'mobily.com',
  'mobily.ws',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'mt2009.com',
  'mt2014.com',
  'myphantomemail.com',
  'myspaceinc.com',
  'myspaceinc.net',
  'myspaceinc.org',
  'myspacepimpedup.com',
  'myspamless.com',
  'mytemp.email',
  'mytempemail.com',
  'mytrashmail.com',
  'mytrashmail.compookmail.com',
  'neverbox.com',
  'no-spam.ws',
  'nobulk.com',
  'noclickemail.com',
  'nogmailspam.info',
  'nomail.xl.cx',
  'nomail2me.com',
  'nomorespamemails.com',
  'nospam.ze.tc',
  'nospam4.us',
  'nospamfor.us',
  'nospamthanks.info',
  'notmailinator.com',
  'nowmymail.com',
  'nurfuerspam.de',
  'objectmail.com',
  'obobbo.com',
  'odnorazovoe.ru',
  'oneoffemail.com',
  'onewaymail.com',
  'onlatedotcom.info',
  'online.ms',
  'opayq.com',
  'ordinaryamerican.net',
  'otherinbox.com',
  'ovpn.to',
  'owlpic.com',
  'pcusers.otherinbox.com',
  'pecinan.com',
  'pecinan.net',
  'pecinan.org',
  'penguinmaster.de',
  'penisgoes.in',
  'pookmail.com',
  'privacy.net',
  'privy-mail.com',
  'privymail.de',
  'proxymail.eu',
  'prtnx.com',
  'putthisinyourspamdatabase.com',
  'pwrby.com',
  'quickinbox.com',
  'rcpt.at',
  'recode.me',
  'recode.net',
  'recode.org',
  'regbypass.com',
  'regbypass.comsafe-mail.net',
  'safersignup.de',
  'safetymail.info',
  'safetypost.de',
  'sandelf.de',
  'saynotospams.com',
  'selfdestructingmail.com',
  'sendspamhere.com',
  'sharklasers.com',
  'shieldemail.com',
  'shieldmail.com',
  'shitmail.me',
  'shitware.nl',
  'shmeriously.com',
  'shortmail.net',
  'sibmail.com',
  'sinnlos-mail.de',
  'slapsfromlastnight.com',
  'slipry.net',
  'slutty.horse',
  'smashmail.de',
  'smellfear.com',
  'snakemail.com',
  'snapwet.com',
  'sneakemail.com',
  'sneakmail.de',
  'snkmail.com',
  'sofimail.com',
  'sofort-mail.de',
  'sogetthis.com',
  'soodonims.com',
  'spam.la',
  'spam4.me',
  'spamail.de',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'spambox.info',
  'spambox.irishrepublican.net',
  'spambox.org',
  'spambox.us',
  'spamcannon.com',
  'spamcannon.net',
  'spamcero.com',
  'spamcon.org',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamcowboy.net',
  'spamcowboy.org',
  'spamday.com',
  'spamex.com',
  'spamfighter.guru',
  'spamfighter.lev.lt',
  'spamfighter.ninja',
  'spamgoes.com',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spamherelots.com',
  'spamhereplease.com',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spamkill.info',
  'spaml.com',
  'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spamoff.de',
  'spamslicer.com',
  'spamspot.com',
  'spamthis.co.uk',
  'spamthisplease.com',
  'spamtrail.com',
  'spamtroll.net',
  'speed.1s.fr',
  'spikio.com',
  'spoofmail.de',
  'stuffmail.de',
  'super-auswahl.de',
  'superrito.com',
  'superrito.com',
  'suremail.info',
  'sweetxxx.de',
  'teewars.org',
  'teleworm.com',
  'teleworm.us',
  'temp-mail.org',
  'temp-mail.ru',
  'tempail.com',
  'tempalias.com',
  'tempe-mail.com',
  'tempemail.biz',
  'tempemail.com',
  'tempinbox.co.uk',
  'tempinbox.com',
  'tempmail.eu',
  'tempmail2.com',
  'tempmaildemo.com',
  'tempmailer.com',
  'tempmailer.de',
  'tempthe.net',
  'thanksnospam.info',
  'thankyou2010.com',
  'thecloudindex.com',
  'thisisnotmyrealemail.com',
  'thisisnotmyrealemail.com',
  'thismail.net',
  'thisurl.website',
  'thrma.com',
  'thrma.com',
  'throam.com',
  'throam.com',
  'throwawayemailaddress.com',
  'tilien.com',
  'tittbit.in',
  'toomail.biz',
  'toomail.com',
  'topranklist.de',
  'tradermail.info',
  'trash-amil.com',
  'trash-mail.at',
  'trash-mail.com',
  'trash-mail.de',
  'trash2009.com',
  'trashemail.de',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmail.ws',
  'trashmailer.com',
  'trashymail.com',
  'trashymail.com',
  'trbvm.com',
  'trbvm.com',
  'trbvm.com',
  'trialmail.de',
  'trillianpro.com',
  'turual.com',
  'twinmail.de',
  'tyldd.com',
  'uggsrock.com',
  'umail.net',
  'uplipht.com',
  'uroid.com',
  'us.af',
  'venompen.com',
  'veryrealemail.com',
  'viditag.com',
  'viewcastmedia.com',
  'viewcastmedia.net',
  'viewcastmedia.org',
  'vollbio.de',
  'vomoto.com',
  'vp.ycare.de',
  'vpn.st',
  'vsimcard.com',
  'vubby.com',
  'walala.org',
  'walkmail.net',
  'webemail.me',
  'webm4il.info',
  'wegwerfadresse.de',
  'wegwerfemail.de',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wegwerpmailadres.nl',
  'wetrainbayarea.com',
  'wetrainbayarea.org',
  'wh4f.org',
  'whatiaas.com',
  'whatpaas.com',
  'whatsaas.com',
  'whopy.com',
  'wilemail.com',
  'willselfdestruct.com',
  'wimsg.com',
  'winemaven.info',
  'wronghead.com',
  'wuzup.net',
  'wuzupmail.net',
  'www.e4ward.com',
  'www.gishpuppy.com',
  'www.mailinator.com',
  'wwwnew.eu',
  'x.ip6.li',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'yapped.net',
  'yeah.net',
  'yep.it',
  'yogamaven.com',
  'yopmail.com',
  'yopmail.net',
  'yopmail.org',
  'ypmail.webarnak.fr.eu.org',
  'yroid.com',
  'yspend.com',
  'yugas.com',
  'yui.it',
  'zehnminuten.de',
  'zehnminutenmail.de',
  'zepp.dk',
  'zippymail.info',
  'zoemail.net',
  'zoemail.org',
  'zomg.info'
]);

/**
 * Validates email format and checks for common typos
 * @param {string} email - Email address to validate
 * @returns {object} - Validation result
 */
function validateEmail(email) {
  if (!email || typeof email !== 'string') {
    return {
      isValid: false,
      reason: 'Invalid format',
      domain: null
    };
  }

  // Basic format validation
  if (!validator.isEmail(email)) {
    return {
      isValid: false,
      reason: 'Invalid format',
      domain: null
    };
  }

  const domain = email.split('@')[1].toLowerCase();
  
  // Check for common typos in popular domains
  const commonDomains = {
    'gmail.com': ['gmaill.com', 'gmial.com', 'gmai.com', 'gmial.com'],
    'hotmail.com': ['hootmail.com', 'hotmial.com', 'hotmai.com'],
    'yahoo.com': ['yahooo.com', 'yaho.com', 'yahoocom'],
    'outlook.com': ['outlok.com', 'outlook.co', 'outlook.coom']
  };

  for (const [correct, typos] of Object.entries(commonDomains)) {
    if (typos.includes(domain)) {
      return {
        isValid: false,
        reason: `Typo detected. Did you mean ${correct}?`,
        domain: domain
      };
    }
  }

  return {
    isValid: true,
    reason: 'Valid format',
    domain: domain
  };
}

/**
 * Checks if domain is in disposable email blacklist
 * @param {string} domain - Domain to check
 * @returns {Promise<object>} - Disposable check result
 */
async function checkDisposableDomain(domain) {
  const normalizedDomain = domain.toLowerCase();
  
  // Check against blacklist
  if (DISPOSABLE_DOMAINS.has(normalizedDomain)) {
    return {
      isDisposable: true,
      reason: 'Blacklist'
    };
  }

  // Check for disposable email patterns
  const disposablePatterns = [
    /temp/i,
    /temporary/i,
    /disposable/i,
    /throwaway/i,
    /trash/i,
    /spam/i,
    /fake/i,
    /test/i
  ];

  for (const pattern of disposablePatterns) {
    if (pattern.test(normalizedDomain)) {
      return {
        isDisposable: true,
        reason: 'Heuristic detection'
      };
    }
  }

  return {
    isDisposable: false,
    reason: 'Valid'
  };
}

/**
 * Checks MX records for the domain
 * @param {string} domain - Domain to check MX records for
 * @returns {Promise<object>} - MX record information
 */
async function checkMXRecords(domain) {
  try {
    const mxRecords = await dns.resolveMx(domain);
    
    if (!mxRecords || mxRecords.length === 0) {
      return {
        primary: null,
        info: 'No MX records found',
        ip: null
      };
    }

    // Sort by priority (lower number = higher priority)
    const sortedMX = mxRecords.sort((a, b) => a.priority - b.priority);
    const primaryMX = sortedMX[0];

    // Try to resolve IP for primary MX
    let ip = null;
    try {
      const ipRecords = await dns.resolve4(primaryMX.exchange);
      ip = ipRecords[0] || null;
    } catch (ipError) {
      // IP resolution failed, but MX exists
    }

    return {
      primary: primaryMX.exchange,
      info: `Using MX pointer ${primaryMX.exchange} from DNS with priority: ${primaryMX.priority}`,
      ip: ip
    };

  } catch (error) {
    return {
      primary: null,
      info: `DNS lookup failed: ${error.message}`,
      ip: null
    };
  }
}

module.exports = {
  validateEmail,
  checkDisposableDomain,
  checkMXRecords
};
